# theme: github-light
background              #FFFFFF
foreground              #1F2328
cursor                  #1F2328
cursor_text_color       #FFFFFF
selection_foreground    #1F2328
selection_background    #D0D7DE
active_tab_background   #F6F8FA
active_tab_foreground   #1F2328
inactive_tab_background #EAECEF
inactive_tab_foreground #6E7781

background_opacity 0.90

color0   #24292F
color1   #CF222E
color2   #1A7F37
color3   #9A6700
color4   #0969DA
color5   #8250DF
color6   #0969A2
color7   #FFFFFF
color8   #57606A
color9   #CF222E
color10  #1A7F37
color11  #BC4C00
color12  #0550AE
color13  #A475F9
color14  #1B7C83
color15  #F6F8FA
